name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run test
      run: |
        echo stating tests
        pip3 install -r requirements.txt
        python3 src/test.py
        echo done
